services:
  localstack:
    image: localstack/localstack:4.4
    container_name: localstack-s3
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 0
      AWS_DEFAULT_REGION: us-east-1
      PERSISTENCE: 1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack-data:
