services:
  localstack:
    image: localstack/localstack:4.4
    container_name: localstack-s3
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,lambda,rekognition
      DEBUG: 0
      AWS_DEFAULT_REGION: us-east-1
      PERSISTENCE: 1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:16
    container_name: upload-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: upload_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d upload_app"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  localstack-data:
  postgres-data:
